[package]
name = "app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "app"
test = false
bench = false

[dependencies]
cortex-m-semihosting = "0.5.0"
rt = { path = "../rt" }
log = { path = "../log" }
